repos:
-   repo: https://github.com/pycqa/flake8
    rev: 'stable' 
    hooks:
    -   id: flake8
        stages: [commit]

  # - repo: local
  #   hooks:
  #     - id: pytest
  #       name: pytest
  #       entry: pytest
  #       language: system
  #       pass_filenames: false
  #       always_run: true
          # stages: [commit]